# Generated by Django 4.2.1 on 2023-05-24 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='location',
        ),
        migrations.AlterField(
            model_name='adsmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.usermodel'),
        ),
        migrations.DeleteModel(
            name='LocModel',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
