# Generated by Django 4.2.1 on 2023-05-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='location',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='locations',
            field=models.ManyToManyField(to='users.locmodel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('member', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='member', max_length=16),
        ),
    ]
