# Generated by Django 4.2.1 on 2023-06-06 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usermodel_location_usermodel_locations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
