# Generated by Django 4.2.1 on 2023-06-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locmodel',
            name='lat',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='locmodel',
            name='lng',
            field=models.FloatField(blank=True),
        ),
    ]
