# Generated by Django 4.2.1 on 2023-06-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_locmodel_lat_alter_locmodel_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locmodel',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locmodel',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='locations',
            field=models.ManyToManyField(blank=True, to='users.locmodel'),
        ),
    ]
