# Generated by Django 4.2.1 on 2023-06-17 21:33

import datetime
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usermodel_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='birth_date',
            field=models.DateField(default=datetime.date(1970, 1, 1), validators=[users.models.check_min_age]),
            preserve_default=False,
        ),
    ]
