# Generated by Django 4.2.1 on 2023-06-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_usermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
